version: "2"

linters:
  default: none
  enable:
    - errcheck
    - staticcheck
    - govet
    - unused
    - ineffassign
    - bodyclose
    - gocritic
  exclusions:
    paths:
      - vendor

settings:
  govet:
    enable:
      - shadow
